"""PC-less Short producer: Drive Takeout footage -> one NEW packaged Short.

Ties together the Drive footage source, the used-segment ledger and the
existing production pipeline, for the scheduled cloud runner that replaces
the retired operator PC:

1. read the channel's own videos (stored youtube_videos snapshot, read-only)
2. for each Takeout archive in the shared Drive folder (oldest first):
   download it, extract only its video files, match each file to its
   channel video (never guessing)
3. order matched videos: confirmed game first, then proven games, longest
4. for the first video with an UNUSED highlight window: register a
   rights-confirmed queue job whose source_url records the exact segment,
   and run the existing highlight -> reframe -> captions -> quality gate ->
   package pipeline on it

It never uploads - publishing stays a separate, private-first step.

Game-title truthfulness: a Short's source title names a game ONLY when the
game is CONFIRMED by console-native metadata (PlayStation's own
#PS4Live/#PS5Live share tags carry the real game). A game that appears only
in an AI-written title or tags is CLAIMED, not confirmed - the channel has
known cases where capture names were wrong - so such Shorts get the neutral
"Archived gameplay" source title and the AI metadata cannot name a game.
"""

from __future__ import annotations

import shutil
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any

import psycopg
import structlog

from .channel_metadata import detect_game
from .clip_selector import HighlightCandidate, WindowSelectorConfig
from .config import Settings
from .database import JobRepository
from .drive_source import (
    ChannelVideoRef,
    DriveArchive,
    download_archive,
    extract_videos,
    list_archives,
    match_all,
)
from .production_runner import ProductionRunResult, highlight_candidates, run_production
from .segment_ledger import fetch_used_segments, first_unused_rank, ledger_url

log = structlog.get_logger()

NEUTRAL_SOURCE_TITLE = "Archived gameplay"

# Games the channel's own data shows performing best come first
# (game-report: Fortnite Shorts carry most of the channel's views).
DEFAULT_GAME_PRIORITY: tuple[str, ...] = (
    "Fortnite",
    "Apex Legends",
    "Roblox",
    "Call of Duty Black Ops",
    "Call of Duty",
)

# Arabic game names used in the channel's own titles/tags. Deliberately as
# conservative as detect_game(): a bare "Black Ops" is never enough.
_ARABIC_GAMES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Fortnite", ("فورتنايت", "فورت نايت")),
    ("Apex Legends", ("أبيكس", "ابيكس", "أبكس", "آبيكس", "آيبيكس", "ايبكس", "إيبكس")),
    ("Roblox", ("روبلكس", "روبلوكس")),
    ("Call of Duty", ("كول أوف ديوتي", "كول اوف ديوتي")),
)

_CONSOLE_NATIVE_TAGS = ("#ps4live", "#ps5live")

CandidateFn = Callable[..., list[HighlightCandidate]]
ProduceFn = Callable[..., ProductionRunResult]



class DriveRunnerError(RuntimeError):
    pass


class GameEvidence(StrEnum):
    CONFIRMED = "confirmed"  # console-native share tags
    CLAIMED = "claimed"  # only in (possibly AI-written) title/tags
    NONE = "none"


@dataclass(frozen=True)
class ChannelVideo:
    video_id: str
    title: str
    duration_seconds: int | None
    tags: tuple[str, ...]

    def ref(self) -> ChannelVideoRef:
        return ChannelVideoRef(self.video_id, self.title, self.duration_seconds)


@dataclass(frozen=True)
class DriveShortResult:
    video_id: str
    source_file: Path
    game: str | None
    evidence: GameEvidence
    source_title: str
    rank: int
    start_seconds: float
    end_seconds: float
    job_id: int
    production: ProductionRunResult


def detect_game_any(text: str) -> str | None:
    """English via the existing conservative detect_game(), plus the Arabic
    game names the channel uses."""
    game = detect_game(text)
    if game:
        return game
    lowered = text.casefold()
    for name, aliases in _ARABIC_GAMES:
        if any(alias in lowered for alias in aliases):
            return name
    return None


def game_evidence(video: ChannelVideo) -> tuple[str | None, GameEvidence]:
    """(game, evidence level) for one channel video."""
    lowered_tags = [tag.casefold() for tag in video.tags]
    if any(tag in _CONSOLE_NATIVE_TAGS for tag in lowered_tags):
        # Console share tags are generated by the PlayStation itself; the
        # game tag next to them names the title actually played.
        for tag in video.tags:
            game = detect_game_any(tag)
            if game:
                return game, GameEvidence.CONFIRMED
    claimed = detect_game_any(video.title) or detect_game_any(" ".join(video.tags))
    if claimed:
        return claimed, GameEvidence.CLAIMED
    return None, GameEvidence.NONE


def source_title_for(game: str | None, evidence: GameEvidence) -> str:
    """Only a CONFIRMED game may appear in the Short's source title."""
    if game and evidence is GameEvidence.CONFIRMED:
        return f"{game} gameplay"
    return NEUTRAL_SOURCE_TITLE


def fetch_channel_videos(settings: Settings) -> list[ChannelVideo]:
    """Current channel videos with a known duration (read-only SELECT)."""
    with psycopg.connect(settings.database_url) as conn:
        rows = conn.execute(
            """
            SELECT video_id, title, duration_seconds, tags
            FROM youtube_videos
            WHERE is_current = TRUE
            ORDER BY published_at ASC NULLS LAST, video_id ASC
            """
        ).fetchall()
    return [
        ChannelVideo(
            video_id=str(video_id),
            title=str(title or ""),
            duration_seconds=duration if isinstance(duration, int) else None,
            tags=tuple(str(t) for t in tags) if isinstance(tags, list) else (),
        )
        for video_id, title, duration, tags in rows
    ]


def probe_duration(path: Path) -> float | None:
    """Container duration in seconds, or None if it cannot be read."""
    try:
        from moviepy import VideoFileClip

        with VideoFileClip(str(path)) as clip:
            return float(clip.duration) if clip.duration else None
    except Exception:
        return None


def order_videos(
    matched: dict[Path, ChannelVideo],
    *,
    game_priority: Sequence[str] = DEFAULT_GAME_PRIORITY,
) -> list[tuple[Path, ChannelVideo, str | None, GameEvidence]]:
    """Confirmed games first, then proven games in priority order, then
    longer videos (more unused footage). Deterministic."""

    def key(item: tuple[Path, ChannelVideo]) -> tuple[int, int, int, str]:
        _path, video = item
        game, evidence = game_evidence(video)
        evidence_rank = {GameEvidence.CONFIRMED: 0, GameEvidence.CLAIMED: 1, GameEvidence.NONE: 2}
        priority = game_priority.index(game) if game in game_priority else len(game_priority)
        return (evidence_rank[evidence], priority, -(video.duration_seconds or 0), video.video_id)

    ordered = sorted(matched.items(), key=key)
    return [(path, video, *game_evidence(video)) for path, video in ordered]


def produce_next_short(
    settings: Settings,
    drive_service: Any,
    folder_id: str,
    *,
    top_n: int = 12,
    game_priority: Sequence[str] = DEFAULT_GAME_PRIORITY,
    channel_videos: Sequence[ChannelVideo] | None = None,
    candidates_fn: CandidateFn = highlight_candidates,
    produce_fn: ProduceFn = run_production,
    duration_fn: Callable[[Path], float | None] = probe_duration,
    repository_factory: Callable[[], JobRepository] | None = None,
) -> DriveShortResult | None:
    """Produce ONE new packaged Short from Drive footage, or None when every
    archive is exhausted (no matched video has an unused window left).
    Never uploads."""
    videos = list(channel_videos) if channel_videos is not None else fetch_channel_videos(settings)
    by_id = {video.video_id: video for video in videos}
    refs = [video.ref() for video in videos]
    selector_config = WindowSelectorConfig(
        min_clip_seconds=settings.highlight_min_seconds,
        max_clip_seconds=settings.highlight_max_seconds,
    )
    make_repository = repository_factory or (
        lambda: JobRepository(settings.database_url, settings.max_job_attempts)
    )

    archives_dir = settings.work_dir / "drive" / "archives"
    extract_root = settings.work_dir / "drive" / "videos"
    cache_dir = settings.work_dir / "analysis"
    cache_dir.mkdir(parents=True, exist_ok=True)

    archives = list_archives(drive_service, folder_id)
    if not archives:
        raise DriveRunnerError(
            f"No Takeout .zip archives found in Drive folder {folder_id}. Is the export "
            "finished, and is the folder shared with the service account?"
        )

    for archive in archives:
        result = _produce_from_archive(
            archive,
            settings,
            drive_service,
            archives_dir=archives_dir,
            extract_dir=extract_root / archive.file_id,
            cache_dir=cache_dir,
            refs=refs,
            by_id=by_id,
            top_n=top_n,
            game_priority=game_priority,
            selector_config=selector_config,
            candidates_fn=candidates_fn,
            produce_fn=produce_fn,
            duration_fn=duration_fn,
            make_repository=make_repository,
        )
        if result is not None:
            return result
    log.info("drive_runner_exhausted", archives=len(archives))
    return None


def _produce_from_archive(
    archive: DriveArchive,
    settings: Settings,
    drive_service: Any,
    *,
    archives_dir: Path,
    extract_dir: Path,
    cache_dir: Path,
    refs: list[ChannelVideoRef],
    by_id: dict[str, ChannelVideo],
    top_n: int,
    game_priority: Sequence[str],
    selector_config: WindowSelectorConfig,
    candidates_fn: CandidateFn,
    produce_fn: ProduceFn,
    duration_fn: Callable[[Path], float | None],
    make_repository: Callable[[], JobRepository],
) -> DriveShortResult | None:
    archive_path = download_archive(drive_service, archive, archives_dir)
    files = extract_videos(archive_path, extract_dir)
    # The extracted videos are all we need; free the archive's disk space
    # (GitHub runners have ~14 GB free).
    archive_path.unlink(missing_ok=True)

    matched_refs, unmatched = match_all([(f, duration_fn(f)) for f in files], refs)
    if unmatched:
        log.info(
            "drive_runner_unmatched_files",
            archive=archive.name,
            count=len(unmatched),
            files=[p.name for p in unmatched][:20],
        )
    matched = {path: by_id[ref.video_id] for path, ref in matched_refs.items()}

    for path, video, game, evidence in order_videos(matched, game_priority=game_priority):
        cache_path = cache_dir / f"drive-{video.video_id}.json"
        candidates = candidates_fn(
            path, top_n, selector_config=selector_config, analysis_cache_path=cache_path
        )
        used = fetch_used_segments(settings, video.video_id)
        rank = first_unused_rank(candidates, used)
        if rank is None:
            log.info("drive_runner_video_exhausted", video_id=video.video_id)
            continue
        candidate = candidates[rank - 1]
        source_title = source_title_for(game, evidence)
        rights_note = (
            f"Cut from the channel's own upload {video.video_id} "
            f"(https://www.youtube.com/watch?v={video.video_id}), segment "
            f"{candidate.start_seconds:.1f}-{candidate.end_seconds:.1f}s, read from the "
            "owner's Google Takeout export. Robin owns this footage. "
            f"Game evidence: {evidence.value}"
            + (f" ({game})." if game else ".")
        )
        repository = make_repository()
        with repository.running():
            job_id = repository.enqueue_local(
                path,
                source_title,
                rights_note,
                source_url=ledger_url(
                    video.video_id, candidate.start_seconds, candidate.end_seconds
                ),
            )
        production = produce_fn(
            job_id,
            rank,
            make_repository(),
            settings,
            selector_config=selector_config,
            analysis_cache_path=cache_path,
        )
        log.info(
            "drive_runner_short_produced",
            video_id=video.video_id,
            job_id=job_id,
            rank=rank,
            game=game,
            evidence=evidence.value,
        )
        return DriveShortResult(
            video_id=video.video_id,
            source_file=path,
            game=game,
            evidence=evidence,
            source_title=source_title,
            rank=rank,
            start_seconds=candidate.start_seconds,
            end_seconds=candidate.end_seconds,
            job_id=job_id,
            production=production,
        )

    shutil.rmtree(extract_dir, ignore_errors=True)
    return None
