"""PC-less Short producer: Drive Takeout footage -> one NEW packaged Short.

Ties together the Drive footage source, the used-segment ledger and the
existing production pipeline, for the scheduled cloud runner that replaces
the retired operator PC:

1. read the channel's own videos (stored youtube_videos snapshot, read-only)
2. for each loose Takeout video (too large for a zip part) and then each
   Takeout archive in the shared Drive folder (oldest first): download it
   only if its title matches a channel video and it fits the runner's free
   disk, extract only the video files of an archive, match each file to its
   channel video (never guessing)
3. order matched videos: confirmed game first, then proven games, longest
4. for the first video with an UNUSED highlight window: register a
   rights-confirmed queue job whose source_url records the exact segment,
   and run the existing highlight -> reframe -> captions -> quality gate ->
   package pipeline on it

It never uploads - publishing stays a separate, private-first step.

Game-title truthfulness: a Short's source title names a game ONLY when the
game is CONFIRMED by console-native metadata (PlayStation's own
#PS4Live/#PS5Live share tags carry the real game). A game that appears only
in an AI-written title or tags is CLAIMED, not confirmed - the channel has
known cases where capture names were wrong - so such Shorts get the neutral
"Archived gameplay" source title and the AI metadata cannot name a game.
"""

from __future__ import annotations

import shutil
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any

import psycopg
import structlog

from .channel_metadata import detect_game
from .clip_selector import HighlightCandidate, WindowSelectorConfig
from .config import Settings
from .database import JobRepository
from .drive_source import (
    ChannelVideoRef,
    DriveArchive,
    DriveVideo,
    download_archive,
    extract_videos,
    list_takeout,
    match_all,
    match_channel_video,
    normalize_title,
)
from .production_runner import ProductionRunResult, highlight_candidates, run_production
from .segment_ledger import (
    fetch_usage_counts,
    fetch_used_segments,
    first_unused_rank,
    ledger_url,
)

log = structlog.get_logger()

NEUTRAL_SOURCE_TITLE = "Archived gameplay"

# Games the channel's own data shows performing best come first
# (game-report: Fortnite Shorts carry most of the channel's views).
DEFAULT_GAME_PRIORITY: tuple[str, ...] = (
    "Fortnite",
    "Apex Legends",
    "Roblox",
    "Call of Duty Black Ops",
    "Call of Duty",
)

# Arabic game names used in the channel's own titles/tags. Deliberately as
# conservative as detect_game(): a bare "Black Ops" is never enough.
_ARABIC_GAMES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Fortnite", ("فورتنايت", "فورت نايت")),
    ("Apex Legends", ("أبيكس", "ابيكس", "أبكس", "آبيكس", "آيبيكس", "ايبكس", "إيبكس")),
    ("Roblox", ("روبلكس", "روبلوكس")),
    ("Call of Duty", ("كول أوف ديوتي", "كول اوف ديوتي")),
)

_CONSOLE_NATIVE_TAGS = ("#ps4live", "#ps5live")

CandidateFn = Callable[..., list[HighlightCandidate]]
ProduceFn = Callable[..., ProductionRunResult]

# Free disk kept for the rendered Short, captions and analysis on top of the
# downloaded footage. Loose Takeout videos can be 17 GB each.
DISK_HEADROOM_BYTES = 3 * 1024**3


class DriveRunnerError(RuntimeError):
    pass


class GameEvidence(StrEnum):
    CONFIRMED = "confirmed"  # console-native share tags
    CLAIMED = "claimed"  # only in (possibly AI-written) title/tags
    NONE = "none"


@dataclass(frozen=True)
class ChannelVideo:
    video_id: str
    title: str
    duration_seconds: int | None
    tags: tuple[str, ...]

    def ref(self) -> ChannelVideoRef:
        return ChannelVideoRef(self.video_id, self.title, self.duration_seconds)


@dataclass(frozen=True)
class DriveShortResult:
    video_id: str
    source_file: Path
    game: str | None
    evidence: GameEvidence
    source_title: str
    rank: int
    start_seconds: float
    end_seconds: float
    job_id: int
    production: ProductionRunResult


def detect_game_any(text: str) -> str | None:
    """English via the existing conservative detect_game(), plus the Arabic
    game names the channel uses."""
    game = detect_game(text)
    if game:
        return game
    lowered = text.casefold()
    for name, aliases in _ARABIC_GAMES:
        if any(alias in lowered for alias in aliases):
            return name
    return None


def game_evidence(video: ChannelVideo) -> tuple[str | None, GameEvidence]:
    """(game, evidence level) for one channel video."""
    lowered_tags = [tag.casefold() for tag in video.tags]
    if any(tag in _CONSOLE_NATIVE_TAGS for tag in lowered_tags):
        # Console share tags are generated by the PlayStation itself; the
        # game tag next to them names the title actually played.
        for tag in video.tags:
            game = detect_game_any(tag)
            if game:
                return game, GameEvidence.CONFIRMED
    claimed = detect_game_any(video.title) or detect_game_any(" ".join(video.tags))
    if claimed:
        return claimed, GameEvidence.CLAIMED
    return None, GameEvidence.NONE


def source_title_for(game: str | None, evidence: GameEvidence) -> str:
    """Only a CONFIRMED game may appear in the Short's source title."""
    if game and evidence is GameEvidence.CONFIRMED:
        return f"{game} gameplay"
    return NEUTRAL_SOURCE_TITLE


def fetch_channel_videos(settings: Settings) -> list[ChannelVideo]:
    """Current channel videos with a known duration (read-only SELECT)."""
    with psycopg.connect(settings.database_url) as conn:
        rows = conn.execute(
            """
            SELECT video_id, title, duration_seconds, tags
            FROM youtube_videos
            WHERE is_current = TRUE
            ORDER BY published_at ASC NULLS LAST, video_id ASC
            """
        ).fetchall()
    return [
        ChannelVideo(
            video_id=str(video_id),
            title=str(title or ""),
            duration_seconds=duration if isinstance(duration, int) else None,
            tags=tuple(str(t) for t in tags) if isinstance(tags, list) else (),
        )
        for video_id, title, duration, tags in rows
    ]


def probe_duration(path: Path) -> float | None:
    """Container duration in seconds, or None if it cannot be read."""
    try:
        from moviepy import VideoFileClip

        with VideoFileClip(str(path)) as clip:
            return float(clip.duration) if clip.duration else None
    except Exception:
        return None


def order_videos(
    matched: dict[Path, ChannelVideo],
    *,
    game_priority: Sequence[str] = DEFAULT_GAME_PRIORITY,
) -> list[tuple[Path, ChannelVideo, str | None, GameEvidence]]:
    """Confirmed games first, then proven games in priority order, then
    longer videos (more unused footage). Deterministic."""

    def key(item: tuple[Path, ChannelVideo]) -> tuple[int, int, int, str]:
        _path, video = item
        game, evidence = game_evidence(video)
        evidence_rank = {GameEvidence.CONFIRMED: 0, GameEvidence.CLAIMED: 1, GameEvidence.NONE: 2}
        priority = game_priority.index(game) if game in game_priority else len(game_priority)
        return (evidence_rank[evidence], priority, -(video.duration_seconds or 0), video.video_id)

    ordered = sorted(matched.items(), key=key)
    return [(path, video, *game_evidence(video)) for path, video in ordered]


def free_disk_bytes(path: Path) -> int:
    return shutil.disk_usage(path).free


@dataclass(frozen=True)
class _RunContext:
    settings: Settings
    drive_service: Any
    refs: list[ChannelVideoRef]
    by_id: dict[str, ChannelVideo]
    known_titles: frozenset[str]
    top_n: int
    game_priority: Sequence[str]
    selector_config: WindowSelectorConfig
    candidates_fn: CandidateFn
    produce_fn: ProduceFn
    duration_fn: Callable[[Path], float | None]
    free_bytes_fn: Callable[[Path], int]
    make_repository: Callable[[], JobRepository]
    work_root: Path
    cache_dir: Path

    def fits_on_disk(self, needed_bytes: int, what: str) -> bool:
        free = self.free_bytes_fn(self.work_root)
        if free >= needed_bytes:
            return True
        log.warning(
            "drive_runner_skipped_no_disk", file=what, needed=needed_bytes, free=free
        )
        return False


def produce_next_short(
    settings: Settings,
    drive_service: Any,
    folder_id: str,
    *,
    top_n: int = 12,
    game_priority: Sequence[str] = DEFAULT_GAME_PRIORITY,
    channel_videos: Sequence[ChannelVideo] | None = None,
    candidates_fn: CandidateFn = highlight_candidates,
    produce_fn: ProduceFn = run_production,
    duration_fn: Callable[[Path], float | None] = probe_duration,
    free_bytes_fn: Callable[[Path], int] = free_disk_bytes,
    usage_fn: Callable[[Settings], dict[str, int]] = fetch_usage_counts,
    repository_factory: Callable[[], JobRepository] | None = None,
) -> DriveShortResult | None:
    """Produce ONE new packaged Short from Drive footage, or None when every
    loose video and archive is exhausted (no matched video has an unused
    window left). Never uploads."""
    videos = list(channel_videos) if channel_videos is not None else fetch_channel_videos(settings)
    refs = [video.ref() for video in videos]
    work_root = settings.work_dir / "drive"
    cache_dir = settings.work_dir / "analysis"
    cache_dir.mkdir(parents=True, exist_ok=True)
    work_root.mkdir(parents=True, exist_ok=True)
    ctx = _RunContext(
        settings=settings,
        drive_service=drive_service,
        refs=refs,
        by_id={video.video_id: video for video in videos},
        known_titles=frozenset(normalize_title(ref.title) for ref in refs) - {""},
        top_n=top_n,
        game_priority=game_priority,
        selector_config=WindowSelectorConfig(
            min_clip_seconds=settings.highlight_min_seconds,
            max_clip_seconds=settings.highlight_max_seconds,
        ),
        candidates_fn=candidates_fn,
        produce_fn=produce_fn,
        duration_fn=duration_fn,
        free_bytes_fn=free_bytes_fn,
        make_repository=repository_factory
        or (lambda: JobRepository(settings.database_url, settings.max_job_attempts)),
        work_root=work_root,
        cache_dir=cache_dir,
    )

    listing = list_takeout(drive_service, folder_id)
    if not listing.archives and not listing.videos:
        raise DriveRunnerError(
            f"No Takeout archives or videos found in Drive folder {folder_id}. Is the "
            "export finished, and is the folder shared with the service account?"
        )

    # Loose videos first: no extraction, and their title (and Drive's own
    # duration, when known) is checked BEFORE anything is downloaded.
    # Rotate sources: the least-used channel video goes first, so consecutive
    # Shorts are not all cut from the same upload.
    for loose in order_loose_videos(listing.videos, ctx, usage_fn(settings)):
        result = _produce_from_loose_video(loose, ctx)
        if result is not None:
            return result
    for archive in listing.archives:
        result = _produce_from_archive(archive, ctx)
        if result is not None:
            return result
    log.info(
        "drive_runner_exhausted",
        archives=len(listing.archives),
        loose_videos=len(listing.videos),
    )
    return None


def order_loose_videos(
    videos: Sequence[DriveVideo], ctx: _RunContext, usage: dict[str, int]
) -> list[DriveVideo]:
    """Loose Takeout videos ordered least-used source first, then by game
    evidence and game priority (as order_videos), then Drive order. Uses
    only the file name (and Drive's duration, when known) - nothing is
    downloaded. Files matching no channel video keep their place at the end
    of the order; _produce_from_loose_video skips them."""
    evidence_rank = {GameEvidence.CONFIRMED: 0, GameEvidence.CLAIMED: 1, GameEvidence.NONE: 2}

    def key(item: tuple[int, DriveVideo]) -> tuple[int, int, int, int]:
        index, loose = item
        name_key = normalize_title(loose.title_name)
        same_title = [ref for ref in ctx.refs if normalize_title(ref.title) == name_key]
        if not same_title:
            return (1, 0, 0, index)
        if loose.duration_seconds is not None:
            ref = match_channel_video(loose.title_name, loose.duration_seconds, ctx.refs)
            if ref is not None:
                same_title = [ref]
        used = min(usage.get(ref.video_id, 0) for ref in same_title)
        best_evidence, best_priority = 2, len(ctx.game_priority)
        for ref in same_title:
            game, evidence = game_evidence(ctx.by_id[ref.video_id])
            priority = (
                ctx.game_priority.index(game)
                if game in ctx.game_priority
                else len(ctx.game_priority)
            )
            best_evidence = min(best_evidence, evidence_rank[evidence])
            best_priority = min(best_priority, priority)
        return (0, used, best_evidence * 100 + best_priority, index)

    return [loose for _, loose in sorted(enumerate(videos), key=key)]


def _produce_from_loose_video(loose: DriveVideo, ctx: _RunContext) -> DriveShortResult | None:
    title_name = loose.title_name
    if normalize_title(title_name) not in ctx.known_titles:
        log.info("drive_runner_unmatched_files", file=loose.name, count=1)
        return None
    if (
        loose.duration_seconds is not None
        and match_channel_video(title_name, loose.duration_seconds, ctx.refs) is None
    ):
        # Title known but Drive's duration singles out no channel video.
        log.info("drive_runner_unmatched_files", file=loose.name, count=1)
        return None
    if not ctx.fits_on_disk((loose.size_bytes or 0) + DISK_HEADROOM_BYTES, loose.name):
        return None

    loose_dir = ctx.work_root / "loose"
    path = download_archive(ctx.drive_service, loose, loose_dir)
    duration = ctx.duration_fn(path)
    if duration is None:
        duration = loose.duration_seconds
    ref = match_channel_video(title_name, duration, ctx.refs)
    result = None
    if ref is None:
        log.info("drive_runner_unmatched_files", file=loose.name, count=1)
    else:
        result = _first_unused_short({path: ctx.by_id[ref.video_id]}, ctx)
    if result is None:
        path.unlink(missing_ok=True)
    return result


def _produce_from_archive(archive: DriveArchive, ctx: _RunContext) -> DriveShortResult | None:
    # The zip plus its extracted videos are on disk at the same time.
    if not ctx.fits_on_disk(2 * (archive.size_bytes or 0) + DISK_HEADROOM_BYTES, archive.name):
        return None
    extract_dir = ctx.work_root / "videos" / archive.file_id
    archive_path = download_archive(ctx.drive_service, archive, ctx.work_root / "archives")
    files = extract_videos(archive_path, extract_dir)
    # The extracted videos are all we need; free the archive's disk space.
    archive_path.unlink(missing_ok=True)

    matched_refs, unmatched = match_all([(f, ctx.duration_fn(f)) for f in files], ctx.refs)
    if unmatched:
        log.info(
            "drive_runner_unmatched_files",
            archive=archive.name,
            count=len(unmatched),
            files=[p.name for p in unmatched][:20],
        )
    result = _first_unused_short(
        {path: ctx.by_id[ref.video_id] for path, ref in matched_refs.items()}, ctx
    )
    if result is None:
        shutil.rmtree(extract_dir, ignore_errors=True)
    return result


def _first_unused_short(
    matched: dict[Path, ChannelVideo], ctx: _RunContext
) -> DriveShortResult | None:
    settings = ctx.settings
    for path, video, game, evidence in order_videos(matched, game_priority=ctx.game_priority):
        cache_path = ctx.cache_dir / f"drive-{video.video_id}.json"
        candidates = ctx.candidates_fn(
            path, ctx.top_n, selector_config=ctx.selector_config, analysis_cache_path=cache_path
        )
        used = fetch_used_segments(settings, video.video_id)
        rank = first_unused_rank(candidates, used)
        if rank is None:
            log.info("drive_runner_video_exhausted", video_id=video.video_id)
            continue
        candidate = candidates[rank - 1]
        source_title = source_title_for(game, evidence)
        rights_note = (
            f"Cut from the channel's own upload {video.video_id} "
            f"(https://www.youtube.com/watch?v={video.video_id}), segment "
            f"{candidate.start_seconds:.1f}-{candidate.end_seconds:.1f}s, read from the "
            "owner's Google Takeout export. Robin owns this footage. "
            f"Game evidence: {evidence.value}"
            + (f" ({game})." if game else ".")
        )
        repository = ctx.make_repository()
        with repository.running():
            job_id = repository.enqueue_local(
                path,
                source_title,
                rights_note,
                source_url=ledger_url(
                    video.video_id, candidate.start_seconds, candidate.end_seconds
                ),
            )
        production = ctx.produce_fn(
            job_id,
            rank,
            ctx.make_repository(),
            settings,
            selector_config=ctx.selector_config,
            analysis_cache_path=cache_path,
        )
        log.info(
            "drive_runner_short_produced",
            video_id=video.video_id,
            job_id=job_id,
            rank=rank,
            game=game,
            evidence=evidence.value,
        )
        return DriveShortResult(
            video_id=video.video_id,
            source_file=path,
            game=game,
            evidence=evidence,
            source_title=source_title,
            rank=rank,
            start_seconds=candidate.start_seconds,
            end_seconds=candidate.end_seconds,
            job_id=job_id,
            production=production,
        )
    return None
